technology:
  title: Technology
  shortDescription: Stay up-to-date with the latest breakthroughs, trends, and news in the world of technology.
  fullDescription: Dive into the ever-evolving world of technology with our comprehensive coverage. From artificial intelligence and virtual reality to cutting-edge gadgets and groundbreaking innovations, we bring you the most relevant and engaging stories. Explore the impact of technology on society, business, and our daily lives, with in-depth articles, expert analysis, and insightful commentary.
  urls:
    - 'https://www.cnet.com/rss/news/'
    - 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml'
    - 'https://moxie.foxnews.com/google-publisher/tech.xml'
business:
  title: Business
  shortDescription: Your source for the latest business news, market trends, and financial insights.
  fullDescription: Stay informed about the dynamic world of business with our in-depth coverage. We bring you breaking news, market analysis, and expert opinions on everything from global finance and economic trends to company profiles and industry developments.  Explore the forces shaping the business landscape and understand their impact on your work, investments, and the global economy.  
  urls:
    - 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml'
    - 'https://fortune.com/feed/fortune-feeds/?id=3230629'
politics:
  title: Politics
  shortDescription: Your source for the latest news and analysis on government, elections, policy, and the forces shaping our world.
  fullDescription: The Politics section provides comprehensive coverage of the ever-evolving political landscape. Stay informed with breaking news, in-depth analysis, and expert commentary on key issues, elections, and the individuals shaping policy at local, national, and international levels.
  urls:
    - 'https://rss.politico.com/politics-news.xml'
    - 'https://feeds.content.dowjones.io/public/rss/socialpoliticsfeed'
    - 'https://moxie.foxnews.com/google-publisher/politics.xml'
sports:
  title: Sports
  shortDescription:  Your one-stop source for live scores, breaking news, in-depth analysis, and highlights from the world of sports.
  fullDescription: The Sports section delivers comprehensive coverage of the diverse and exciting world of athletics, from amateur competitions to professional leagues and international tournaments.  Stay up-to-date with the latest scores, news, and analysis across a variety of sports.
  urls:
    - 'https://moxie.foxnews.com/google-publisher/sports.xml'
    - 'https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml'
